
DROP TABLE TEST_AUTH_USERS;
CREATE TABLE TEST_AUTH_USERS
  (ID_USERS NUMBER(10),
   EMAIL VARCHAR2(50),
   USERNAME VARCHAR2(50),
   PASSWORD VARCHAR2(255),
   DATE_INSCRIPTION DATE,
   BIO VARCHAR2(2000),
   ISADMIN NUMBER(10));

DROP SEQUENCE SEQ_TEST_AUTH_USERS;
CREATE SEQUENCE SEQ_TEST_AUTH_USERS START WITH 1 INCREMENT BY 1;



DROP TABLE TEST_AUTH_MESSAGES;
CREATE TABLE TEST_AUTH_MESSAGES
  (ID_MESSAGES NUMBER(10),
   ID_USERS NUMBER(10),
   TITLE VARCHAR2(50),
   CONTENT VARCHAR2(2000),
   ATTACHMENT VARCHAR2(255),
   LIKES INT(20));

DROP SEQUENCE SEQ_TEST_AUTH_MESSAGES;
CREATE SEQUENCE SEQ_TEST_AUTH_MESSAGES START WITH 1 INCREMENT BY 1;




DROP TABLE SIA_AUTHENTIFICATION;
CREATE TABLE SIA_AUTHENTIFICATION
  (ID_SIA_AUTHENTIFICATION NUMBER(20),
   IDENTIFIANTS VARCHAR2(30),
   MOTDEPASSE VARCHAR2(100),
   DATE_INSCRIPTION DATE,
   NOM VARCHAR2(20),
   PRENOM VARCHAR2(20),
   EMAIL VARCHAR2(100),
   PROFIL VARCHAR2(20));

DROP SEQUENCE SEQ_SIA_AUTHENTIFICATION;
CREATE SEQUENCE SEQ_SIA_AUTHENTIFICATION START WITH 1 INCREMENT BY 1;



DROP TABLE SIA_FORM_DIMA;
CREATE TABLE SIA_FORM_DIMA
  (ID_SIA_FORM_DIMA NUMBER(20),
   DATE_DEMANDE DATE,
   NOM_DEMANDE VARCHAR2(30),
   NOM VARCHAR2(20),
   PRENOM VARCHAR2(20),
   IDENTIFICATION_FONCTION_CHEFSERVICE_POLE VARCHAR2(30),
   IDENTIFICATION_FONCTION_MEDECIN VARCHAR2(30),
   IDENTIFICATION_FONCTION_INTERNE VARCHAR2(30),
   IDENTIFICATION_FONCTION_CADRE VARCHAR2(30),
   IDENTIFICATION_FONCTION_CADRE_GESTIONNAIRE VARCHAR2(30),
   IDENTIFICATION_FONCTION_DIRECTEUR VARCHAR2(30),
   IDENTIFICATION_FONCTION_AUTRE VARCHAR2(100),
   SERVICE_RATTACHEMENT VARCHAR2(100),
   COORDONNEES VARCHAR2(100),
   MAIL VARCHAR2(100),
   TELEPHONE NUMBER(20),
   REFERENT_MEDICAL VARCHAR2(100),
   DEMANDE_TRAVAIL_ACADEMIQUE VARCHAR2(30),
   DEMANDE_RECHERCHE VARCHAR2(30),
   DEMANDE_SUIVI_ACTIVITE_EPRD VARCHAR2(30),
   DEMANDE_CONTROLE_QUALITE VARCHAR2(30),
   DEMANDE_ANALYSE_THEMATIQUE VARCHAR2(30),
   DEMANDE_REGISTRE VARCHAR2(30),
   DEMANDE_AUTRE VARCHAR2(30),
   CONTEXTE VARCHAR2(30),
   CRITERE_INCLUSION VARCHAR2(30),
   CRITERE_EXCLUSION VARCHAR2(30),
   PERIODE_DONNEES_DEMANDEES VARCHAR2(30),
   PERIMETRE_ETUDE_VOTRE_SERVICE VARCHAR2(30),
   PERIMETRE_PLUSIEURS_SERVICES_CHU VARCHAR2(50),
   PERIMETRE_PLUSIEURS_ETABLISSEMENT_FRANCE VARCHAR2(50),
   PERIMETRE_PLUSIEURS_ETABLISSEMENT_FRANCE_ETRANGER VARCHAR2(50),
   RESTITUTION_FORMAT_LISTE_NON_IDENTIFIANTE VARCHAR2(30),
   RESTITUTION_FORMAT_LISTE_IDENTIFIANTE VARCHAR2(30),
   RESTITUTION_FORMAT_DONNEES_AGREGEES VARCHAR2(30),
   RESTITUTION_FORMAT_RAPPORT VARCHAR2(30),
   VARIABLES_SOUHAITEES VARCHAR2(30),
   DELAI_ETUDE VARCHAR2(30));

DROP SEQUENCE SEQ_SIA_FORM_DIMA;
CREATE SEQUENCE SEQ_SIA_FORM_DIMA START WITH 1 INCREMENT BY 1;


DROP TABLE SIA_FORM_RECHERCHE;
CREATE TABLE SIA_FORM_RECHERCHE
  (ID_SIA_FORM_RECHERCHE NUMBER(20),
   DATE_DEMANDE DATE,
   NOM_DEMANDE VARCHAR2(30),
   NOM VARCHAR2(20),
   PRENOM VARCHAR2(20),
   IDENTIFICATION_FONCTION_CHEFSERVICE_POLE VARCHAR2(30),
   IDENTIFICATION_FONCTION_MEDECIN VARCHAR2(30),
   IDENTIFICATION_FONCTION_INTERNE VARCHAR2(30),
   IDENTIFICATION_FONCTION_CADRE VARCHAR2(30),
   IDENTIFICATION_FONCTION_CADRE_GESTIONNAIRE VARCHAR2(30),
   IDENTIFICATION_FONCTION_DIRECTEUR VARCHAR2(30),
   IDENTIFICATION_FONCTION_AUTRE VARCHAR2(100),
   SERVICE_RATTACHEMENT VARCHAR2(100),
   COORDONNEES VARCHAR2(100),
   MAIL VARCHAR2(100),
   TELEPHONE NUMBER(20),
   REFERENT_MEDICAL VARCHAR2(100),
   PROJET_CONTEXTE_POSITIONNEMENT VARCHAR2(300),
   PROJET_OBJECTIF_PRINCIPAL VARCHAR2(300),
   CRITERE_INCLUSION VARCHAR2(30),
   CRITERE_EXCLUSION VARCHAR2(30),
   PERIODE_DONNEES_DEMANDEES VARCHAR2(30),
   PERIMETRE_ETUDE_VOTRE_SERVICE VARCHAR2(30),
   PERIMETRE_PLUSIEURS_SERVICES_CHU VARCHAR2(50),
   PERIMETRE_PLUSIEURS_ETABLISSEMENT_FRANCE VARCHAR2(50),
   PERIMETRE_PLUSIEURS_ETABLISSEMENT_FRANCE_ETRANGER VARCHAR2(50),
   DETAIL_TYPE_DONNEES VARCHAR2(300),
   PUBLICATION_FORM_RESULTAT VARCHAR2(100),
   PROJET_MOYEN_HUMAIN_FINANCIER VARCHAR2(300),
   DELAI_ETUDE VARCHAR2(30));

DROP SEQUENCE SIA_FORM_RECHERCHE;
CREATE SEQUENCE SIA_FORM_RECHERCHE START WITH 1 INCREMENT BY 1;







